---
# all.sample.yml

#
# Config
#

cephadm_conf: []
cephadm_conf_commands: []

#
# Dashboard
#

cephadm_dashboard: true
cephadm_dashboard_password: "admin"
cephadm_dashboard_username: "admin"

#
# Firewall
#

cephadm_firewall_firewalld: true

#
# Network
#

cephadm_network_private_interface: "eno1"
cephadm_network_private_ips: []
cephadm_network_private_vip: ""
cephadm_network_public_interface: "{{ cephadm_network_private_interface }}"
cephadm_network_public_ips: "{{ cephadm_network_private_ips }}"
cephadm_network_public_vip: "{{ cephadm_network_private_vip }}"

#
# OSDs
#

cephadm_osd_cpus: 1

cephadm_osd_devices:
  fast:
    block:
      - /dev/sdb

cephadm_osd_memory: 1gb
cephadm_osd_per_hdd: 1
cephadm_osd_per_nvme: 4
cephadm_osd_per_ssd: 2

#
# Python
#

cephadm_python_version: "{{ ansible_python_version }}"
cephadm_python_major_version: "{{ ansible_python.version.major }}"
cephadm_python_minor_version: "{{ ansible_python.version.minor }}"
