# sample.all.yml

#
# Config
#

cephadm_config:
  - >-
    ceph osd erasure-code-profile set host-2-1-jerasure
    crush-failure-domain=host k=2 m=1 plugin=jerasure
  - >-
    ceph osd erasure-code-profile set host-2-2-jerasure
    crush-failure-domain=host k=2 m=2 plugin=jerasure
  - >-
    ceph osd erasure-code-profile set host-4-2-jerasure
    crush-failure-domain=host k=4 m=2 plugin=jerasure
  - >-
    ceph osd erasure-code-profile set host-8-3-jerasure
    crush-failure-domain=host k=8 m=3 plugin=jerasure

#
# Dashboard
#

# Whether the dashboard should be deployed.
cephadm_dashboard: true

# The username and password to use for the administrative user
cephadm_dashboard_password: admin
cephadm_dashboard_username: admin

# The IP address and port(s) to use for the dashboard
cephadm_dashboard_server_addr: >-
  "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"
cephadm_dashboard_server_port: 8080
cephadm_dashboard_server_port_ssl: 8443

# Add your own certs to the dashboard, if desired.  Maybe I should
# see about using LetsEncrypt to make/manage SSLs across the
# deployment.
cephadm_dashboard_ssl_crt: ""
cephadm_dashboard_ssl_key: ""

#
# Firewall
#

cephadm_firewall_firewalld: false

#
# Health
#

# Placeholder
cephadm_health_mon_check: ""

#
# Mon
#

# Placeholder
cephadm_mon: ""

#
# Network
#

# 'cephadm_network_ip_version' defines whether you want to use IPv4 or
# IPv6 in your cluster.
cephadm_network_ip_version: ipv4

# 'cephadm_network_interface_cluster' refers to the private network
# used by Ceph, in this case isolated to a specific network interface.
#
# By default we assume that the current default ipv4 interface will be
# used for this purpose, though this is highly likely to be different
# in production use cases.
cephadm_network_interface_cluster: "{{ ansible_default_ipv4.interface }}"

# 'cephadm_network_interface_public' refers to the public network used
# by Ceph, in this case isolated to a specific network interface.
#
# By default we assume that all network traffic should simply refer to
# the defined cluster interface, though this is highly likely to be
# different in production use cases.
cephadm_network_interface_public: "{{ cephadm_network_interface_cluster }}"

# The following interfaces are predefined to use the canonical cluster
# or public interfaces based on common Ceph idioms.  In some cases you
# may wish to further isolate services, so the additional control to
# do so is provided.
cephadm_network_interface_mgrs: "{{ cephadm_network_interface_cluster }}"
cephadm_network_interface_mons: "{{ cephadm_network_interface_public }}"
cephadm_network_interface_osds: "{{ cephadm_network_interface_cluster }}"
cephadm_network_interface_rgws: "{{ cephadm_network_interface_public }}"

#
# OSDs
#

# https://docs.ceph.com/en/octopus/cephadm/drivegroups/
cephadm_osd_drivegroups:
  - service_type: osd
    service_id: default_drive_group
    placement:
      host_pattern: "*"
    data_devices:
      rotational: 1
    db_devices:
      rotational: 0

#
# Pools
#

# These are the defaults for all pools created _by this playbook_, so
# that we can trim as much verbosity from pool definitions as possible.
cephadm_pool_default_pg_num: 100
cephadm_pool_default_pgp_num: 100
cephadm_pool_default_type: "replicated" # "replicated", "erasure"
cephadm_pool_default_application: "rbd" # "rbd", "cephfs", "rgw"
cephadm_pool_default_compression: "raw" # "raw", "lz4", "zlib", "zstd"
cephadm_pool_default_autoscale_mode: true # "on"|true, "off"|false, "warn"

# The pools listed here are the minimum pools required by OpenStack and
# should be changed with caution.
cephadm_pools:
  - name: "backups"
  - name: "images"
  - name: "manilla_data"
    application: "cephfs"
  - name: "manilla_metadata"
    application: "cephfs"
  - name: "metrics"
  - name: "vms"
  - name: "volumes"

#
# Openstack
#

openstack_enabled: false

openstack_keys:
  - name: client.cinder
    caps:
      mon: { profile: "rbd" }
      osd: { profile: "rbd", pools: ["vms", "volumes"] }
      mode: "0600"
  - name: client.cinder-backup
    caps:
      mon: { profile: "rbd" }
      osd: { profile: "rbd", pools: ["backups"] }
      mode: "0600"
  - name: client.glance
    caps:
      mon: { profile: "rbd" }
      osd: { profile: "rbd", pools: ["images", "volumes"] }
      mode: "0600"
  - name: client.gnocchi
    caps:
      mon: { profile: "rbd" }
      osd: { profile: "rbd", pools: ["metrics"] }
      mode: "0600"
  - name: client.openstack
    caps:
      mon: { profile: "rbd" }
      osd: { profile: "rbd", pools: ["backups", "images", "vms", "volumes"] }
      mode: "0600"

#
# RGW
#

cephadm_rgw_realm: default
cephadm_rgw_zone: default
cephadm_rgw_zonegroup: default
