---
# site.deploy.yml

- name: Check hosts and configuration for issues
  any_errors_fatal: true
  gather_facts: false
  hosts: all
  tags: [always, check]

  pre_tasks:
    - name: check if Python 3 is present
      raw: |-
        command -v python3
      changed_when: false

    - name: gather facts
      setup:
        gather_subset: all

  roles:
    - cephadm-check

- name: Bootstrap the cluster
  any_errors_fatal: true
  gather_facts: false
  hosts: all
  tags: [bootstrap]

  roles:
    - cephadm-bootstrap
