---
# site.deploy.yml

- name: check if hosts are eligible
  any_errors_fatal: true
  gather_facts: false
  hosts: all
  tags: always

  roles:
    - role: cephadm-check

- name: check configuration for issues
  any_errors_fatal: true
  gather_facts: false
  hosts: all
  tags: always

  roles:
    - role: cephadm-facts
# - name: Bootstrap the first host
#   any_errors_fatal: true
#   gather_facts: false
#   hosts: mons[0]
#   tags: bootstrap

#   roles:
#     - role: cephadm-bootstrap

# - name: Add monitors
#   any_errors_fatal: true
#   gather_facts: false
#   hosts: mons!mons[0]
#   tags: mons

#   roles:
#     - role: cephadm-mon

# - name: Setup OSDs
#   any_errors_fatal: true
#   gather_facts: false
#   hosts: osds
#   tags: osds

#   roles:
#     - role: cephadm-osd
