---
# site.deploy.yml

- name: Prerequisites
  any_errors_fatal: true
  gather_facts: false
  hosts: all
  tags: always

  pre_tasks:
    - name: check if some version of Python is installed
      raw: |-
        command -v python || command -v python2 || command -v python3
      register: python_installed
      changed_when: false

    - name: Gather facts
      setup:

  tasks:
    - name: check if host OS is supported
      fail:
        msg: "Reported host OS {{ target }} not supported"
      changed_when: false
      failed_when: target not in targets
      vars:
        target: "{{ ansible_distribution }}-{{ ansible_distribution_version }}"
        targets:
          - Ubuntu-18.04

  roles:
    - role: cephadm-facts
      tags: [always]

    - role: cephadm-check
      tags: [check]

# - name: Bootstrap
#   any_errors_fatal: true
#   gather_facts: false
#   hosts: mons[0]
#   tags: bootstrap

#   roles:
#     - role: cephadm-bootstrap

# - name: Add monitors
#   any_errors_fatal: true
#   gather_facts: false
#   hosts: mons!mons[0]
#   tags: mons

#   roles:
#     - role: cephadm-mon

# - name: Setup OSDs
#   any_errors_fatal: true
#   gather_facts: false
#   hosts: osds
#   tags: osds

#   roles:
#     - role: cephadm-osd
