# site-deploy.yml

- name: Check
  any_errors_fatal: true
  gather_facts: false
  hosts: all
  tags: [always]
  roles:
    - role: cephadm-check
      tags: [check]

- name: Setup
  any_errors_fatal: true
  gather_facts: false
  hosts: all
  tags: [setup]
  roles:
    - cephadm-setup

- name: Deploy
  any_errors_fatal: true
  gather_facts: false
  hosts: mons[0]
  tags: [deploy]
  roles:
    - role: cephadm-bootstrap
      tags: [bootstrap]

    - roles: cephadm-dashboard
      tags: [dashboard]

    - role: cephadm-mon
      tags: [never, mon]

    - role: cephadm-mgr
      tags: [never, mgr]

    - role: cephadm-osd
      tags: [never, osd]
