# site.yml

- name: Prepare
  any_errors_fatal: true
  gather_facts: false
  hosts: all
  roles:
    - role: cephadm-check
      tags: [always, check, checks]

    - role: cephadm-setup
      tags: [setup]

- name: Deploy
  any_errors_fatal: true
  gather_facts: false
  hosts: mons[0]
  tags: [deploy]
  roles:
    - role: cephadm-bootstrap
      tags: [bootstrap]

    - role: cephadm-dashboard
      tags: [dashboard, dashboards]

    - role: cephadm-mon
      tags: [mon, mons]

    - role: cephadm-mgr
      tags: [mgr, mgrs]

    - role: cephadm-osd
      tags: [never, osd, osds]

    - role: cephadm-rgw
      tags: [never, rgw, rgws]
