---
# site.deploy.yml

- name: Bootstrap the first ceph-mon host
  any_errors_fatal: true
  tags: always
  hosts: mons[0]

  pre_tasks:
    - name: Install package dependencies
      package:
        name: "{{ ceph_package_dependencies }}"
        state: present
      vars:
        ceph_package_dependencies:
          - docker.io
          - python-pip

    - name: Start package services
      service:
        name: "{{ item }}"
        state: started
      with_items:
        - docker

    - name: Install pip dependencies
      pip:
        name: "{{ ceph_pip_dependencies }}"
        state: present
      vars:
        ceph_pip_dependencies:
          - cephadm>=1.0.0,<2.0.0
          - docker>=4.1.0,<5.0.0

  # tasks:
  #   # TODO: allow using a defined interface _OR_ a specific IP address
  #   - name: Add local mgr/mons daemons, generate Ceph/SSH keys, and ceph.conf
  #     command: |-
  #       cephadm bootstrap
  #       --skip-ping-check
  #       {{ "--skip-dashboard" if not ceph_dashboard else omit }}
  #       {{ if ceph_dashboard --initial-dashboard-user ceph_dashboard_username --initial-dashboard-password ceph_dashboard_password }}
  #       --mon-ip {{ ansible_facts[ceph_network_private_interface]['ipv4'][0]['address'] }}

#     # TODO: Do we really need to prep the container now?
#     - name: Mount Ceph utilities container and expose to host
#       command: |-
#         cephadm shell
#         --config ceph.conf
#         --keyring ceph.client.admin.keyring

#     # TODO: hosts wouldn't be authed with each other, so this wouldn't
#     # actually work.
#     - name: Sync Ceph keys
#       synchronize:
#         src: /fake/path
#         dest: "rsync://{{ item }}/wew/lad"
#       with_inventory_hostnames:
#         - all!mons[0]

# - name: Deploy additional monitors
#   any_errors_fatal: true
#   tags: always
#   hosts: mons[0]

# - name: Create OSDs
#   any_errors_fatal: true
#   tags: always
#   hosts: mons[0]
