# site-deploy.yml

- name: Check
  any_errors_fatal: true
  gather_facts: false
  hosts: all
  tags: [always]
  roles:
    - role: cephadm-check
      tags: [check]

- name: Setup
  any_errors_fatal: true
  gather_facts: false
  hosts: all
  tags: [setup]
  roles:
    - cephadm-setup

- name: Bootstrap
  any_errors_fatal: true
  gather_facts: false
  hosts: mons[0]
  tags: [bootstrap]
  roles:
    - cephadm-bootstrap

- name: Dashboard
  any_errors_fatal: true
  gather_facts: false
  hosts: mons[0]
  tags: [dashboard]
  roles:
    - cephadm-dashboard

- name: Add ceph-mon(s)
  any_errors_fatal: true
  gather_facts: false
  hosts: mons[0]
  tags: [never, mon]
  roles:
    - cephadm-mon

- name: Add ceph-mgr(s)
  any_errors_fatal: true
  gather_facts: false
  hosts: mgrs
  tags: [never, mgr]
  roles:
    - cephadm-mgr

- name: Add ceph-osd(s)
  any_errors_fatal: true
  gather_facts: false
  hosts: osds
  tags: [never, osd]
  roles:
    - cephadm-osd
