# site-deploy.yml

- name: Check
  any_errors_fatal: true
  gather_facts: false
  hosts: all
  tags: [always]
  roles:
    - role: cephadm-check
      tags: [check]

- name: Bootstrap
  any_errors_fatal: true
  gather_facts: false
  hosts: mons[0]
  tags: [bootstrap]
  roles:
    - cephadm-bootstrap

- name: Add ceph-mon(s)
  any_errors_fatal: true
  gather_facts: false
  hosts: mons[0]
  tags: [mon]
  roles:
    - cephadm-mon

- name: Add ceph-mgr(s)
  any_errors_fatal: true
  gather_facts: false
  hosts: mgrs
  tags: [mgr]
  roles:
    - cephadm-mgr

- name: Add ceph-osd(s)
  any_errors_fatal: true
  gather_facts: false
  hosts: osds
  tags: [osd]
  roles:
    - cephadm-osd
