---
# site.deploy.yml

- name: Prerequisites
  any_errors_fatal: true
  gather_facts: false
  hosts: all

  pre_tasks:
    - name: check if Python 3 is present
      raw: |-
        command -v python3
      register: python_installed
      changed_when: false

    - name: gather facts
      setup:
        gather_subset: all

  roles:
    - role: cephadm-facts
    - role: cephadm-check
