---
# facts.yml
#
# This file examines all defined variables and sets them as facts.  In
# the event that an expected variable is undefined, we will set the
# default value.
#
# No silent adjustments of variables should occur.  If you find that a
# variable has been silently changed here, it is considered a severe
# issue that _must_ be resolved.

- name: Build dict of variables, types, and default values
  set_fact:
    variables:
      - var: cephadm_conf
        type: iterable
        default:
      - var: cephadm_conf_commands
        type: iterable
        default:
      - var: cephadm_dashboard
        type: boolean
        default:
      - var: cephadm_dashboard_password
        type: string
        default:
      - var: cephadm_dashboard_username
        type: string
        default:
      - var: cephadm_firewall_firewalld
        type: boolean
        default:
      - var: cephadm_network_private_interface
        type: string
        default:
      - var: cephadm_network_private_ips
        type: iterable
        default:
      - var: cephadm_network_private_vip
        type: string
        default:
      - var: cephadm_network_public_interface
        type: string
        default:
      - var: cephadm_network_public_ips
        type: iterable
        default:
      - var: cephadm_network_public_vip
        type: string
        default:
      - var: cephadm_osd_cpus
        type: number
        default: 1
      - var: cephadm_osd_devices
        type: iterable
        default: []
      - var: cephadm_osd_memory
        type: string
        default: 1gb
      - var: cephadm_osd_per_hdd
        type: number
        default: 1
      - var: cephadm_osd_per_nvme
        type: number
        default: 4
      - var: cephadm_osd_per_ssd
        type: number
        default: 2
      - var: cephadm_python_version
        type: number
        default: ansible_python_version
      - var: cephadm_python_major_version
        type: number
        default: ansible_python.version.major
      - var: cephadm_python_minor_version
        type: number
        default: ansible_python.version.minor

- name: Set cephadm facts
  set_fact:
    "{{ var }}": >-
      {{ var
      if var is defined
      else default }}
  vars:
    var: "{{ item.var }}"
    type: "{{ item.type }}"
    default: "{{ item.default }}"
  with_items: "{{ variables }}"

- name: fail if variables have improper types
  fail:
    msg: >-
      The variable '{{ var }}' is invalid.  Please ensure it is
      defined and is of type '{{ type }}'.
  failed_when: >-
    {{ var }} is undefined
    or {{ var }} is not {{ type }}
  vars:
    var: "{{ item.var }}"
    type: "{{ item.type }}"
  with_items: "{{ variables }}"
