---
- name: yea
  set_fact:
    variables:
      - var: cephadm_conf
        type: iterable
        default:
      - var: cephadm_conf_commands
        type: iterable
        default:
      - var: cephadm_dashboard
        type: boolean
        default:
      - var: cephadm_dashboard_password
        type: string
        default:
      - var: cephadm_dashboard_username
        type: string
        default:
      - var: cephadm_firewall_firewalld
        type: boolean
        default:
      - var: cephadm_network_private_interface
        type: string
        default:
      - var: cephadm_network_private_ips
        type: iterable
        default:
      - var: cephadm_network_private_vip
        type: string
        default:
      - var: cephadm_network_public_interface
        type: string
        default:
      - var: cephadm_network_public_ips
        type: iterable
        default:
      - var: cephadm_network_public_vip
        type: string
        default:
      - var: cephadm_osd_cpus
        type: number
        default: 1
      - var: cephadm_osd_devices
        type: iterable
        default: []
      - var: cephadm_osd_memory
        type: string
        default: 1gb
      - var: cephadm_osd_per_hdd
        type: number
        default: 1
      - var: cephadm_osd_per_nvme
        type: number
        default: 4
      - var: cephadm_osd_per_ssd
        type: number
        default: 2
      - var: cephadm_python_version
        type: number or string
        default: "{{ ansible_python_version }}"
      - var: cephadm_python_major_version
        type: number
        default: "{{ ansible_python.version.major }}"
      - var: cephadm_python_minor_version
        type: number or string
        default: "{{ ansible_python.version.minor }}"

- name: fail if variables have improper types
  fail:
    msg: >-
      The variable '{{ var }}' is invalid.  Please ensure it is
      defined and is of type '{{ type }}'.
  failed_when: >-
    {{ var }} is undefined
    or ({{ var }} is {{ type }}) == 'False'
  vars:
    var: "{{ item.var }}"
    type: "{{ item.type }}"
    default: "{{ item.type }}"
  with_items: "{{ variables }}"
