# facts.yml

- name: Set cephadm_hosts_* facts for easy references
  set_fact:
    cephadm_hosts: >-
      {{ ansible_play_hosts_all | unique }}
    cephadm_hosts_list: >-
      {% for host in ansible_play_hosts_all | unique -%}
      {{ host }}{% if not loop.last %},{% endif -%}
      {% endfor %}

    cephadm_hosts_mgrs: >-
      {{ groups.mgrs | unique }}
    cephadm_hosts_mgrs_list: >-
      {% for host in groups.mgrs | unique -%}
      {{ host }}{% if not loop.last %},{% endif -%}
      {% endfor %}

    cephadm_hosts_mons: >-
      {{ groups.mons | unique }}
    cephadm_hosts_mons_list: >-
      {% for host in groups.mons | unique -%}
      {{ host }}{% if not loop.last %},{% endif -%}
      {% endfor %}

    cephadm_hosts_osds: >-
      {{ groups.osds | unique }}
    cephadm_hosts_osds_list: >-
      {% for host in groups.osds | unique -%}
      {{ host }}{% if not loop.last %},{% endif -%}
      {% endfor %}

    cephadm_hosts_rgws: >-
      {{ groups.rgws | unique }}
    cephadm_hosts_rgws_list: >-
      {% for host in groups.rgws | unique -%}
      {{ host }}{% if not loop.last %},{% endif -%}
      {% endfor %}

    cephadm_hosts_rgwlbs: >-
      {{ groups.rgwlbs | unique }}
    cephadm_hosts_rgwlbs_list: >-
      {% for host in groups.rgwlbs | unique -%}
      {{ host }}{% if not loop.last %},{% endif -%}
      {% endfor %}

- name: Set cephadm configuration facts
  set_fact:
    cephadm_conf: >-
      {{ cephadm_conf | default({}) }}
    cephadm_conf_commands: >-
      {{ cephadm_conf_commands | default([]) }}

    cephadm_dashboard: >-
      {{ cephadm_dashboard | default(true) }}
    cephadm_dashboard_password: >-
      {{ cephadm_dashboard_password | default('admin') }}
    cephadm_dashboard_username: >-
      {{ cephadm_dashboard_username | default('admin') }}

    cephadm_firewall_firewalld: >-
      {{ cephadm_firewall_firewalld | default(true) }}

    cephadm_network_interface_cluster: >-
      {{ cephadm_network_interface_cluster | default('') }}
    cephadm_network_interface_public: >-
      {{ cephadm_network_interface_public | default(cephadm_network_interface_cluster) }}
    cephadm_network_interface_mgrs: >-
      {{ cephadm_network_interface_mgrs | default(cephadm_network_interface_cluster) }}
    cephadm_network_interface_mons: >-
      {{ cephadm_network_interface_mons | default(cephadm_network_interface_public) }}
    cephadm_network_interface_osds: >-
      {{ cephadm_network_interface_osds | default(cephadm_network_interface_cluster) }}
    cephadm_network_interface_rgws: >-
      {{ cephadm_network_interface_rgws | default(cephadm_network_interface_public) }}

    cephadm_network_vip_cluster: >-
      {{ cephadm_network_vip_cluster | default('') }}
    cephadm_network_vip_public: >-
      {{ cephadm_network_vip_public | default('') }}

    cephadm_osd_cpus: >-
      {{ cephadm_osd_cpus | default(1) }}
    cephadm_osd_drivegroups: >-
      {{ cephadm_osd_drivegroups | default({}) }}
    cephadm_osd_memory: >-
      {{ (cephadm_osd_memory | human_to_bytes)
      if cephadm_osd_memory is defined
      else ('1 GB' | human_to_bytes) }}
    cephadm_osd_per_hdd: >-
      {{ cephadm_osd_per_hdd | default(1) }}
    cephadm_osd_per_nvme: >-
      {{ cephadm_osd_per_nvme | default(4) }}
    cephadm_osd_per_ssd: >-
      {{ cephadm_osd_per_ssd | default(2) }}
