# facts.yml

- name: Set cephadm_hosts_* facts for easy references
  set_fact:
    cephadm_hosts: >-
      {{ ansible_play_hosts_all | unique }}
    cephadm_hosts_list: >-
      {% for host in ansible_play_hosts_all | unique -%}
      {{ host }}{% if not loop.last %},{% endif -%}
      {% endfor %}

    cephadm_hosts_mgrs: >-
      {{ groups.mgrs | unique }}
    cephadm_hosts_mgrs_list: >-
      {% for host in groups.mgrs | unique -%}
      {{ host }}{% if not loop.last %},{% endif -%}
      {% endfor %}

    cephadm_hosts_mons: >-
      {{ groups.mons | unique }}
    cephadm_hosts_mons_list: >-
      {% for host in groups.mons | unique -%}
      {{ host }}{% if not loop.last %},{% endif -%}
      {% endfor %}

    cephadm_hosts_osds: >-
      {{ groups.osds | unique }}
    cephadm_hosts_osds_list: >-
      {% for host in groups.osds | unique -%}
      {{ host }}{% if not loop.last %},{% endif -%}
      {% endfor %}

    cephadm_hosts_rgws: >-
      {{ groups.rgws | unique }}
    cephadm_hosts_rgws_list: >-
      {% for host in groups.rgws | unique -%}
      {{ host }}{% if not loop.last %},{% endif -%}
      {% endfor %}

    cephadm_hosts_rgwlbs: >-
      {{ groups.rgwlbs | unique }}
    cephadm_hosts_rgwlbs_list: >-
      {% for host in groups.rgwlbs | unique -%}
      {{ host }}{% if not loop.last %},{% endif -%}
      {% endfor %}

- name: Set conf facts
  set_fact:
    cephadm_config: >-
      {{ cephadm_config | default({}) }}

- name: Set dashboard facts
  set_fact:
    cephadm_dashboard: >-
      {{ cephadm_dashboard | default(True) }}
    cephadm_dashboard_password: >-
      {{ cephadm_dashboard_password | default('admin') }}
    cephadm_dashboard_username: >-
      {{ cephadm_dashboard_username | default('admin') }}

- name: Set firewall facts
  set_fact:
    cephadm_firewall_firewalld: >-
      {{ cephadm_firewall_firewalld | default(True) }}

- name: Set network facts
  set_fact:
    cephadm_network_interface_cluster: >-
      {{ cephadm_network_interface_cluster | default('') }}
    cephadm_network_interface_public: >-
      {{ cephadm_network_interface_public | default(cephadm_network_interface_cluster) }}
    cephadm_network_interface_mgrs: >-
      {{ cephadm_network_interface_mgrs | default(cephadm_network_interface_cluster) }}
    cephadm_network_interface_mons: >-
      {{ cephadm_network_interface_mons | default(cephadm_network_interface_public) }}
    cephadm_network_interface_osds: >-
      {{ cephadm_network_interface_osds | default(cephadm_network_interface_cluster) }}
    cephadm_network_interface_rgws: >-
      {{ cephadm_network_interface_rgws | default(cephadm_network_interface_public) }}

- name: Set additional network facts
  set_fact:
    cephadm_network_interfaces:
      - "{{ cephadm_network_interface_cluster }}"
      - "{{ cephadm_network_interface_public }}"
      - "{{ cephadm_network_interface_mgrs }}"
      - "{{ cephadm_network_interface_mons }}"
      - "{{ cephadm_network_interface_osds }}"
      - "{{ cephadm_network_interface_rgws }}"

- name: Set OSD facts
  set_fact:
    cephadm_osd_drivegroups: >-
      {{ cephadm_osd_drivegroups | default({}) }}

- name: Set RGW facts
  set_fact:
    cephadm_rgw_realm: >-
      {{ cephadm_rgw_realm | default('ceph') }}
    cephadm_rgw_zone: >-
      {{ cephadm_rgw_zone | default('use-east-1') }}
    cephadm_rgw_zonegroup: >-
      {{ cephadm_rgw_zone | default('default') }}
