---
# cephadm-check/tasks/facts.yml

- name: Set cephadm facts
  set_fact:
    cephadm_conf: >-
      {{ cephadm_conf | default({}) }}
    cephadm_conf_commands: >-
      {{ cephadm_conf_commands | default([]) }}

    cephadm_dashboard: >-
      {{ cephadm_dashboard | default(true) }}
    cephadm_dashboard_password: >-
      {{ cephadm_dashboard_password | default('admin') }}
    cephadm_dashboard_username: >-
      {{ cephadm_dashboard_username | default('admin') }}

    cephadm_firewall_firewalld: >-
      {{ cephadm_firewall_firewalld | default(true) }}

    cephadm_network_private_interface: >-
      {{ cephadm_network_private_interface | default('') }}
    cephadm_network_private_ips: >-
      {{ cephadm_network_private_ips | default([]) }}
    cephadm_network_private_vip: >-
      {{ cephadm_network_private_vip | default('') }}
    cephadm_network_public_interface: >-
      {{ cephadm_network_public_interface | default('') }}
    cephadm_network_public_ips: >-
      {{ cephadm_network_public_ips | default([]) }}
    cephadm_network_public_vip: >-
      {{ cephadm_network_public_vip | default('') }}

    cephadm_osd_cpus: >-
      {{ cephadm_osd_cpus | default(1) }}
    cephadm_osd_devices: >-
      {{ cephadm_osd_devices | default({}) }}
    cephadm_osd_memory: >-
      {{ (cephadm_osd_memory | human_to_bytes)
      if cephadm_osd_memory is defined
      else ('1 GB' | human_to_bytes) }}
    cephadm_osd_per_hdd: >-
      {{ cephadm_osd_per_hdd | default(1) }}
    cephadm_osd_per_nvme: >-
      {{ cephadm_osd_per_nvme | default(4) }}
    cephadm_osd_per_ssd: >-
      {{ cephadm_osd_per_ssd | default(2) }}
