# cephadm-check/tasks/facts.yml

- name: Set cephadm_hosts_* facts for easy references
  set_fact:
    cephadm_hosts: "{{ ansible_play_hosts_all | unique }}"
    cephadm_hosts_list: "{{ ansible_play_hosts_all | unique | list }}"
    cephadm_hosts_mgrs: "{{ groups.mgrs | unique }}"
    cephadm_hosts_mgrs_list: "{{ groups.mgrs | unique | list }}"
    cephadm_hosts_mons: "{{ groups.mons | unique }}"
    cephadm_hosts_mons_list: "{{ groups.mons | unique | list }}"
    cephadm_hosts_osds: "{{ groups.osds | unique }}"
    cephadm_hosts_osds_list: "{{ groups.osds | unique | list }}"
    cephadm_hosts_rgws: "{{ groups.rgws | unique }}"
    cephadm_hosts_rgws_list: "{{ groups.rgws | unique | list }}"
    cephadm_hosts_rgwlbs: "{{ groups.rgwlbs | unique }}"
    cephadm_hosts_rgwlbs_list: "{{ groups.rgwlbs | unique | list }}"

#
# cephadm_conf
#

- name: Set config facts
  set_fact:
    cephadm_config: "{{ cephadm_config | default([]) }}"

- name: check 'cephadm_config'
  fail:
    msg: |
      Invalid value for variable 'cephadm_config': {{ cephadm_config }}

      Supported types  : mapping
      Supported values : []  <- Too many possible values to list
      Default value    : []
  failed_when: >-
    cephadm_config is not iterable
    or cephadm_config is string

#
# cephadm_dashboard
#

- name: Set dashboard facts
  set_fact:
    cephadm_dashboard: "{{ cephadm_dashboard | default(True) }}"
    cephadm_dashboard_password: >-
      {{ cephadm_dashboard_password | default('admin') }}
    cephadm_dashboard_username: >-
      {{ cephadm_dashboard_username | default('admin') }}

- name: check 'cephadm_dashboard'
  fail:
    msg: |
      Invalid value for variable 'cephadm_dashboard': {{ cephadm_dashboard }}

      Supported types  : boolean
      Supported values : true, false
      Default value    : true
  failed_when: >-
    cephadm_dashboard is not boolean
    or cephadm_dashboard not in [true, false]

- name: check 'cephadm_dashboard_password'
  fail:
    msg: |
      Invalid value for variable 'cephadm_dashboard_password': {{ cephadm_dashboard_password }}

      Supported types  : string
      Supported values : Any quoted string
      Default value    : "admin"
  failed_when: cephadm_dashboard_password is not string

- name: check 'cephadm_dashboard_username'
  fail:
    msg: |
      Invalid value for variable 'cephadm_dashboard_username': {{ cephadm_dashboard_username }}

      Supported types  : string
      Supported values : Any quoted string
      Default value    : "admin"
  failed_when: cephadm_dashboard_username is not string

#
# cephadm_firewall
#

- name: Set firewall facts
  set_fact:
    cephadm_firewall_firewalld: >-
      {{ cephadm_firewall_firewalld | default(True) }}

- name: check 'cephadm_firewall_firewalld'
  fail:
    msg: |
      Invalid value for variable 'cephadm_firewall_firewalld': {{ cephadm_firewall_firewalld }}

      Supported types  : boolean
      Supported values : true, false
      Default value    : true
  failed_when: >-
    cephadm_firewall_firewalld is not boolean
    or cephadm_firewall_firewalld not in [true, false]

#
# cephadm_network
#

- name: Set network facts
  set_fact:
    cephadm_network_ip_version: >-
      {{ cephadm_network_ip_version | lower | default('ipv4')}}
    cephadm_network_interface_cluster: >-
      {{ cephadm_network_interface_cluster
      | default(ansible_default_ipv4.interface) }}
    cephadm_network_interface_public: >-
      {{ cephadm_network_interface_public
      | default(cephadm_network_interface_cluster) }}
    cephadm_network_interface_mgrs: >-
      {{ cephadm_network_interface_mgrs
      | default(cephadm_network_interface_cluster) }}
    cephadm_network_interface_mons: >-
      {{ cephadm_network_interface_mons
      | default(cephadm_network_interface_public) }}
    cephadm_network_interface_osds: >-
      {{ cephadm_network_interface_osds
      | default(cephadm_network_interface_cluster) }}
    cephadm_network_interface_rgws: >-
      {{ cephadm_network_interface_rgws
      | default(cephadm_network_interface_public) }}

- name: check 'cephadm_network_ip_version'
  fail:
    msg: |
      Invalid value for variable 'cephadm_network_ip_version': {{ cephadm_network_ip_version }}

      Supported types  : string
      Supported values : "ipv4", "ipv6"
      Default value    : "ipv4"
  failed_when: >-
    cephadm_network_ip_version is not string
    or cephadm_network_ip_version not in ["ipv4", "ipv6"]

- name: check 'cephadm_network_interface_cluster'
  fail:
    msg: |
      Invalid value for variable 'cephadm_network_interface_cluster': {{ cephadm_network_interface_cluster }}

      Supported types  : string
      Supported values : Any quoted network interface name
      Default value    : "{{ ansible_default_ipv4.interface }}" from ansible_default_ipv4.interface
  failed_when: cephadm_network_interface_cluster is not string

- name: check 'cephadm_network_interface_public'
  fail:
    msg: |
      Invalid value for variable 'cephadm_network_interface_public': {{ cephadm_network_interface_public }}

      Supported types  : string
      Supported values : Any quoted network interface name
      Default value    : "{{ ansible_default_ipv4.interface }}" from ansible_default_ipv4.interface
  failed_when: cephadm_network_interface_public is not string

- name: check 'cephadm_network_interface_mgrs'
  fail:
    msg: |
      Invalid value for variable 'cephadm_network_interface_mgrs': {{ cephadm_network_interface_mgrs }}

      Supported types  : string
      Supported values : Any quoted network interface name
      Default value    : "{{ ansible_default_ipv4.interface }}" from ansible_default_ipv4.interface
  failed_when: cephadm_network_interface_mgrs is not string

- name: check 'cephadm_network_interface_mons'
  fail:
    msg: |
      Invalid value for variable 'cephadm_network_interface_mons': {{ cephadm_network_interface_mons }}

      Supported types  : string
      Supported values : Any quoted network interface name
      Default value    : "{{ ansible_default_ipv4.interface }}" from ansible_default_ipv4.interface
  failed_when: cephadm_network_interface_mons is not string

- name: check 'cephadm_network_interface_osds'
  fail:
    msg: |
      Invalid value for variable 'cephadm_network_interface_osds':
      {{ cephadm_network_interface_osds }}

      Supported types  : string
      Supported values : Any quoted network interface name
      Default value    : "{{ ansible_default_ipv4.interface }}" from ansible_default_ipv4.interface
  failed_when: cephadm_network_interface_osds is not string

- name: check 'cephadm_network_interface_rgws'
  fail:
    msg: |
      Invalid value for variable 'cephadm_network_interface_rgws': {{ cephadm_network_interface_rgws }}

      Supported types  : string
      Supported values : Any quoted network interface name
      Default value    : "{{ ansible_default_ipv4.interface }}" from ansible_default_ipv4.interface
  failed_when: cephadm_network_interface_rgws is not string

- name: Set macro 'cephadm_network_interfaces' fact
  set_fact:
    cephadm_network_interfaces:
      - "{{ cephadm_network_interface_cluster }}"
      - "{{ cephadm_network_interface_public }}"
      - "{{ cephadm_network_interface_mgrs }}"
      - "{{ cephadm_network_interface_mons }}"
      - "{{ cephadm_network_interface_osds }}"
      - "{{ cephadm_network_interface_rgws }}"

- name: check if 'cephadm_network_interfaces' exist
  fail:
    msg: >-
      The interface '{{ item }}' found in 'cephadm_network_interfaces'
      does not exist.  Please review your defined network interfaces
      for errors.
  failed_when: item not in ansible_facts.interfaces
  with_items: "{{ cephadm_network_interfaces | unique }}"

- name: check if 'cephadm_network_interfaces' are reachable
  command: ping -c 1 "{{ target.address }}"
  changed_when: false
  vars:
    interface: "{{ item[1] }}"
    ipver: "{{ cephadm_network_ip_version }}"
    target: "{{ hostvars[item[0]]['ansible_' + interface][ipver] }}"
  with_nested:
    - "{{ cephadm_hosts }}"
    - "{{ cephadm_network_interfaces | unique }}"

#
# cephadm_osd
#

- name: Set OSD facts
  set_fact:
    cephadm_osd_drivegroups: >-
      {{ cephadm_osd_drivegroups | default([]) }}

- name: check 'cephadm_osd_drivegroups'
  fail:
    msg: |
      Invalid value for variable 'cephadm_osd_drivegroups': {{ cephadm_osd_drivegroups }}

      Supported types  : list
      Supported values : []  <- Too many possible values to list
      Default value    : []
  failed_when: >-
    cephadm_osd_drivegroups is not iterable
    or cephadm_osd_drivegroups is string

#
# cephadm_pool
#

- name: Set Pool facts
  set_fact:
    cephadm_pool_default_pg_num: >-
      {{ cephadm_pool_default_pg_num | default(100) }}
    cephadm_pool_default_pgp_num: >-
      {{ cephadm_pool_default_pgp_num | default(100) }}
    cephadm_pool_default_type: >-
      {{ cephadm_pool_default_type | default("replicated") }}
    cephadm_pool_default_application: >-
      {{ cephadm_pool_default_application | default("rbd") }}
    cephadm_pool_default_compression: >-
      {{ cephadm_pool_default_compression | default("raw") }}
    cephadm_pool_default_autoscale_mode: >-
      {{ cephadm_pool_default_autoscale_mode | default(true) }}
    cephadm_pools: "{{ cephadm_pools | default([]) }}"

- name: Set cephadm_pools_list
  set_fact:
    cephadm_pools_list: "{{ pools.split(' ') }}"
  vars:
    pools: >-
      {% for pool in cephadm_pools -%}
      {{ pool.name }}{% if not loop.last %} {% endif %}
      {%- endfor -%}

- name: check 'cephadm_pool_default_pg_num'
  fail:
    msg: |
      Invalid value for variable 'cephadm_pool_default_pg_num': {{ cephadm_pool_default_pg_num }}

      Supported types  : number
      Supported values : 1 or greater
      Default value    : 100
  failed_when: cephadm_pool_default_pg_num|int < 1

- name: check 'cephadm_pool_default_pgp_num'
  fail:
    msg: |
      Invalid value for variable 'cephadm_pool_default_pgp_num': {{ cephadm_pool_default_pgp_num }}

      Supported types  : number
      Supported values : 1 or greater
      Default value    : 100
  failed_when: cephadm_pool_default_pgp_num|int < 1

- name: check 'cephadm_pool_default_type'
  fail:
    msg: |
      Invalid value for variable 'cephadm_pool_default_type': {{ cephadm_pool_default_type }}

      Supported types  : string
      Supported values : "replicated", "erasure"
      Default value    : "replicated"
  failed_when: >-
    cephadm_pool_default_type is not string
    or cephadm_pool_default_type not in ["replicated", "erasure"]

- name: check 'cephadm_pool_default_application'
  fail:
    msg: |
      Invalid value for variable 'cephadm_pool_default_application': {{ cephadm_pool_default_application }}

      Supported types  : string
      Supported values : "rbd", "cephfs", "rgw"
      Default value    : "rbd"
  failed_when: >-
    cephadm_pool_default_application is not string
    or cephadm_pool_default_application not in ["rbd", "cephfs", "rgw"]

- name: check 'cephadm_pool_default_compression'
  fail:
    msg: |
      Invalid value for variable 'cephadm_pool_default_compression': {{ cephadm_pool_default_compression }}

      Supported types  : string
      Supported values : "raw", "lz4", "zlib", "zstd"
      Default value    : "raw"
  failed_when: >-
    cephadm_pool_default_compression is not string
    or cephadm_pool_default_compression not in ["raw", "lz4", "zlib", "zstd"]

- name: check 'cephadm_pool_default_autoscale_mode'
  fail:
    msg: |
      Invalid value for variable 'cephadm_pool_default_autoscale_mode': {{ cephadm_pool_default_autoscale_mode }}

      Supported types  : boolean
      Supported values : true|"on", false|"off", "warn"
      Default value    : true
  failed_when: >-
    (cephadm_pool_default_autoscale_mode is not boolean
    or cephadm_pool_default_autoscale_mode not in [true, false])
    and (cephadm_pool_default_autoscale_mode is not string
    or cephadm_pool_default_autoscale_mode not in ["on", "off", "warn"])

- name: check 'cephadm_pools'
  fail:
    msg: |
      Invalid value for variable 'cephadm_pools': {{ cephadm_pools }}

      Supported types  : list
      Supported values : []  <- Too many possible values to list
      Default value    : []
  failed_when: >-
    cephadm_pools is not iterable
    or cephadm_pools is string

#
# cephadm_rgw
#

- name: Set RGW facts
  set_fact:
    cephadm_rgw_realm: >-
      {{ cephadm_rgw_realm | default('ceph') }}
    cephadm_rgw_zone: >-
      {{ cephadm_rgw_zone | default('use-east-1') }}
    cephadm_rgw_zonegroup: >-
      {{ cephadm_rgw_zone | default('default') }}

- name: check 'cephadm_rgw_realm'
  fail:
    msg: |
      Invalid value for variable 'cephadm_rgw_realm': {{ cephadm_rgw_realm }}

      Supported types  : string
      Supported values : Any quoted string
      Default value    : "default"
  failed_when: cephadm_rgw_realm is not string

- name: check 'cephadm_rgw_zone'
  fail:
    msg: |
      Invalid value for variable 'cephadm_rgw_zone': {{ cephadm_rgw_zone }}

      Supported types  : string
      Supported values : Any quoted string
      Default value    : "default"
  failed_when: cephadm_rgw_zone is not string

- name: check 'cephadm_rgw_zonegroup'
  fail:
    msg: |
      Invalid value for variable 'cephadm_rgw_zonegroup': {{ cephadm_rgw_zonegroup }}

      Supported types  : string
      Supported values : Any quoted string
      Default value    : "default"
  failed_when: cephadm_rgw_zonegroup is not string

#
# openstack
#

- name: Set OpenStack facts
  set_fact:
    openstack_enabled: "{{ openstack_enabled | default(false) }}"
    openstack_keys: "{{ openstack_keys | default([]) }}"

- name: check 'openstack_enabled'
  fail:
    msg: |
      Invalid value for variable 'openstack_enabled': {{ openstack_enabled }}

      Supported types  : boolean
      Supported values : true, false
      Default value    : false
  failed_when: >-
    openstack_enabled is not boolean
    or openstack_enabled not in [true, false]

- name: check 'openstack_keys'
  fail:
    msg: |
      Invalid value for variable 'openstack_keys': {{ openstack_keys }}

      Supported types  : list
      Supported values : []  <- Too many possible values to list
      Default value    : []
  failed_when: >-
    openstack_keys is not iterable
    or openstack_keys is string

- name: check items in 'openstack_keys'
  fail:
    msg: |
      Invalid value for item in 'openstack_keys': {{ item }}

      Supported types  : mapping, various
      Supported values : name: string
                         caps: mapping
                         mon: mapping
                         osd: mapping
                         profile: string
                         pools: iterable, only strings
                         mode: "number"
      Missing pools    : {{item.caps.osd.pools|difference(cephadm_pools_list)}}
      Default value    : {}  <- Too many possible values to list
  failed_when: >-
    item is not mapping
    or item is string
    or item.name is not string
    or "client" not in item.name
    or item.caps is not mapping
    or item.caps is string
    or item.caps.mode is not string
    or item.caps.mode|int < 1
    or item.caps.mon is not mapping
    or item.caps.mon is string
    or item.caps.mon.profile is not string
    or item.caps.mon.profile not in ["rbd"]
    or item.caps.osd is not mapping
    or item.caps.osd is string
    or item.caps.osd.profile is not string
    or item.caps.osd.profile not in ["rbd"]
    or item.caps.osd.pools is not iterable
    or item.caps.osd.pools is string
    or item.caps.osd.pools | difference(cephadm_pools_list)
  loop_control:
    label: "{{ item.name }}"
  with_items:
    - "{{ openstack_keys }}"
