---
- name: check if Python 3 is present
  raw: |-
    command -v python3 || command -v python3.6
  register: python_installed
  changed_when: false

- name: gather facts
  setup:
    gather_subset: all

- name: check if host OS is supported
  fail:
    msg: >-
      Host OS {{ ansible_distribution }} {{ ansible_distribution_release }}
      is not fully supported.  Please see
      https://docs.ceph.com/docs/master/releases/octopus/
      for more information.
  changed_when: false
  failed_when:
    - ansible_distribution not in targets.keys()
    - ansible_distribution_release not in releases
  vars:
    targets:
      CentOS: ["8"]
      Debian: ["buster"]
      Ubuntu: ["bionic"]
    releases: "{{ targets[ansible_distribution] }}"
