---
# cephadm-check/tasks/main.yml

- name: Check if Python3 is installed
  raw: >-
    command -v python3
  changed_when: false

- name: Gather facts
  setup:
    gather_subset: all

- name: Check if host OS is supported
  fail:
    msg: >-
      Host OS {{ ansible_distribution }} {{ ansible_distribution_release }}
      is not fully supported.  Please see
      https://docs.ceph.com/docs/master/releases/octopus/
      for more information.
  failed_when: >-
    ansible_distribution not in targets.keys()
    or (ansible_distribution_release not in versions
    and ansible_distribution_major_version not in versions)
  vars:
    targets:
      CentOS: ["8"]
      Debian: ["buster"]
      Ubuntu: ["bionic"]
    versions: "{{ targets[ansible_distribution] }}"

- name: Set defined variables as facts
  include: facts.yml

- name: Check types of defined variables for issues
  include: types.yml

- name: Check values of defined variables for issues
  include: values.yml
