---
# cephadm-check/tasks/main.yml

- name: Set defined variables as facts
  include: facts.yml

- name: Check types of defined variables for issues
  include: types.yml

- name: Check values of defined variables for issues
  include: values.yml
  tags: [never]
