---
# cephadm-check/tasks/types.yml

#
# cephadm_conf
#

- name: check if var 'cephadm_config' is type 'mapping'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_config':
      {{ cephadm_config }}
  failed_when: >-
    cephadm_config is not mapping

#
# cephadm_dashboard
#

- name: check if 'cephadm_dashboard' is type 'boolean'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_dashboard':
      {{ cephadm_dashboard }}
  failed_when: >-
    cephadm_dashboard is not boolean

- name: check if 'cephadm_dashboard_password' is type 'string'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_dashboard_password':
      {{ cephadm_dashboard_password }}
  failed_when: >-
    cephadm_dashboard_password is not string

- name: check if 'cephadm_dashboard_username' is type 'string'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_dashboard_username':
      {{ cephadm_dashboard_username }}
  failed_when: >-
    cephadm_dashboard_username is not string

#
# cephadm_firewall
#

- name: check if 'cephadm_firewall_firewalld' is type 'boolean'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_firewall_firewalld':
      {{ cephadm_firewall_firewalld }}
  failed_when: >-
    cephadm_firewall_firewalld is not boolean

#
# cephadm_network
#

- name: check if 'cephadm_network_interface_cluster' is type 'string'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_network_interface_cluster':
      {{ cephadm_network_interface_cluster }}
  failed_when: >-
    cephadm_network_interface_cluster is not string

- name: check if 'cephadm_network_interface_public' is type 'string'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_network_interface_public':
      {{ cephadm_network_interface_public }}
  failed_when: >-
    cephadm_network_interface_public is not string

- name: check if 'cephadm_network_interface_mgrs' is type 'string'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_network_interface_mgrs':
      {{ cephadm_network_interface_mgrs }}
  failed_when: >-
    cephadm_network_interface_mgrs is not string

- name: check if 'cephadm_network_interface_mons' is type 'string'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_network_interface_mons':
      {{ cephadm_network_interface_mons }}
  failed_when: >-
    cephadm_network_interface_mons is not string

- name: check if 'cephadm_network_interface_osds' is type 'string'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_network_interface_osds':
      {{ cephadm_network_interface_osds }}
  failed_when: >-
    cephadm_network_interface_osds is not string

- name: check if 'cephadm_network_interface_rgws' is type 'string'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_network_interface_rgws':
      {{ cephadm_network_interface_rgws }}
  failed_when: >-
    cephadm_network_interface_rgws is not string

#
# cephadm_osd
#

- name: check if 'cephadm_osd_drivegroups' is type 'mapping'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_osd_drivegroups':
      {{ cephadm_osd_drivegroups }}
  failed_when: >-
    cephadm_osd_drivegroups is not mapping

#
# cephadm_rgw
#

- name: check if 'cephadm_rgw_realm' is type 'string'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_rgw_realm':
      {{ cephadm_rgw_realm }}
  failed_when: >-
    cephadm_rgw_realm is not string

- name: check if 'cephadm_rgw_zone' is type 'string'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_rgw_zone':
      {{ cephadm_rgw_zone }}
  failed_when: >-
    cephadm_rgw_zone is not string

- name: check if 'cephadm_rgw_zonegroup' is type 'string'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_rgw_zonegroup':
      {{ cephadm_rgw_zonegroup }}
  failed_when: >-
    cephadm_rgw_zonegroup is not string
