---
# cephadm-check/tasks/types.yml

#
# cephadm_conf
#

- name: check if var 'cephadm_conf' is type 'mapping'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_conf':
      {{ cephadm_conf }}
  failed_when: >-
    cephadm_conf is not mapping

- name: check if 'cephadm_conf_commands' is type 'iterable'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_conf_commands':
      {{ cephadm_conf_commands }}
  failed_when: >-
    cephadm_conf_commands is not iterable
    or cephadm_conf_commands is string

#
# cephadm_dashboard
#

- name: check if 'cephadm_dashboard' is type 'boolean'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_dashboard':
      {{ cephadm_dashboard }}
  failed_when: >-
    cephadm_dashboard is not boolean

- name: check if 'cephadm_dashboard_password' is type 'string'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_dashboard_password':
      {{ cephadm_dashboard_password }}
  failed_when: >-
    cephadm_dashboard_password is not string

- name: check if 'cephadm_dashboard_username' is type 'string'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_dashboard_username':
      {{ cephadm_dashboard_username }}
  failed_when: >-
    cephadm_dashboard_username is not string

#
# cephadm_firewall
#

- name: check if 'cephadm_firewall_firewalld' is type 'boolean'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_firewall_firewalld':
      {{ cephadm_firewall_firewalld }}
  failed_when: >-
    cephadm_firewall_firewalld is not boolean

#
# cephadm_network
#

- name: check if 'cephadm_network_interface_cluster' is type 'string'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_network_interface_cluster':
      {{ cephadm_network_interface_cluster }}
  failed_when: >-
    cephadm_network_interface_cluster is not string

- name: check if 'cephadm_network_interface_public' is type 'string'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_network_interface_public':
      {{ cephadm_network_interface_public }}
  failed_when: >-
    cephadm_network_interface_public is not string

- name: check if 'cephadm_network_interface_monitor' is type 'string'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_network_interface_monitor':
      {{ cephadm_network_interface_monitor }}
  failed_when: >-
    cephadm_network_interface_monitor is not string

- name: check if 'cephadm_network_interface_radosgw' is type 'string'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_network_interface_radosgw':
      {{ cephadm_network_interface_radosgw }}
  failed_when: >-
    cephadm_network_interface_radosgw is not string

- name: check if 'cephadm_network_vip_cluster' is type 'string'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_network_vip_cluster':
      {{ cephadm_network_vip_cluster }}
  failed_when: >-
    cephadm_network_vip_public is not string
    and cephadm_network_vip_public is iterable

- name: check if 'cephadm_network_vip_public' is type 'iterable'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_network_vip_public':
      {{ cephadm_network_vip_public }}
  failed_when: >-
    cephadm_network_vip_public is not string
    and cephadm_network_vip_public is iterable

#
# cephadm_osd
#

- name: check if 'cephadm_osd_cpus' is type 'number'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_osd_cpus':
      {{ cephadm_osd_cpus }}
  failed_when: >-
    cephadm_osd_cpus | int < 1

- name: check if 'cephadm_osd_drivegroups' is type 'mapping'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_osd_drivegroups':
      {{ cephadm_osd_drivegroups }}
  failed_when: >-
    cephadm_osd_drivegroups is not mapping

- name: check if 'cephadm_osd_memory' is type 'number'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_osd_memory':
      {{ cephadm_osd_memory | filesizeformat(true) }}
  failed_when: >-
    cephadm_osd_memory | int < 1

- name: check if 'cephadm_osd_per_hdd' is type 'number'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_osd_per_hdd':
      {{ cephadm_osd_per_hdd }}
  failed_when: >-
    cephadm_osd_per_hdd | int < 1

- name: check if 'cephadm_osd_per_nvme' is type 'number'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_osd_per_nvme':
      {{ cephadm_osd_per_nvme }}
  failed_when: >-
    cephadm_osd_per_nvme | int < 1

- name: check if 'cephadm_osd_per_ssd' is type 'number'
  fail:
    msg: >-
      Invalid value for variable 'cephadm_osd_per_ssd':
      {{ cephadm_osd_per_ssd }}
  failed_when: >-
    cephadm_osd_per_ssd | int < 1
