# values.yml

- name: check if cephadm_network_interfaces exist
  fail:
    msg: "The interface {{ item }} does not exist"
  failed_when: item not in ansible_facts.interfaces
  with_items: "{{ cephadm_network_interfaces | unique }}"

- name: check if cephadm_network_interfaces are reachable
  command: >-
    ping -c 1 "{{ target.address }}"
  changed_when:
    - result.rc is defined
    - result.rc > 0
  register: result
  vars:
    interface: "{{ item[1] }}"
    ipver: "{{ cephadm_network_ip_version }}"
    target: "{{ hostvars[item[0]]['ansible_' + interface][ipver] }}"
  with_nested:
    - "{{ cephadm_hosts }}"
    - "{{ cephadm_network_interfaces | unique }}"

- name: check if cephadm_osd_drivegroups is defined and populated
  fail:
    msg: >-
      No storage devices defined in cephadm_osd_drivegroups!
  changed_when: false
  failed_when:
    - cephadm_osd_drivegroups is undefined
    - (cephadm_osd_drivegroups | length) < 1
