# values.yml

- name: check if defined network interfaces exist
  fail:
    msg: "The interface {{ item }} does not exist"
  failed_when: item not in ansible_facts.interfaces
  vars:
    interfaces:
      - "{{ cephadm_network_interface_cluster }}"
      - "{{ cephadm_network_interface_public }}"
      - "{{ cephadm_network_interface_mgrs }}"
      - "{{ cephadm_network_interface_mons }}"
      - "{{ cephadm_network_interface_osds }}"
      - "{{ cephadm_network_interface_rgws }}"
  with_items: "{{ interfaces | unique }}"

- name: check if all Cluster Network interfaces are reachable
  command: >-
    ping -c 1 "{{ target.address }}"
  changed_when: false
  vars:
    interface: "{{ cephadm_network_interface_cluster }}"
    interfaces:
      - "{{ cephadm_network_interface_cluster }}"
      - "{{ cephadm_network_interface_public }}"
      - "{{ cephadm_network_interface_mgrs }}"
      - "{{ cephadm_network_interface_mons }}"
      - "{{ cephadm_network_interface_osds }}"
      - "{{ cephadm_network_interface_rgws }}"
    ipver: "{{ cephadm_network_ip_version }}"
    target: "{{ hostvars[item[0]]['ansible_' + interface][ipver] }}"
  with_nested:
    - "{{ cephadm_hosts }}"
    - "{{ interfaces | unique }}"

- name: check if cephadm_osd_drivegroups is defined and populated
  fail:
    msg: >-
      No storage devices defined in cephadm_osd_drivegroups!
  changed_when: false
  failed_when:
    - cephadm_osd_drivegroups is undefined
    - (cephadm_osd_drivegroups | length) < 1
