# packages.yml

- name: (Debian) Add Ceph key
  apt_key:
    state: present
    url: https://download.ceph.com/keys/release.asc

- name: (Debian) Add Ceph repository
  apt_repository:
    filename: ceph
    repo: deb https://download.ceph.com/debian-octopus/ {{ ansible_distribution_release }} main
    state: present
    update_cache: false

- name: (Debian) Update APT cache
  apt:
    cache_valid_time: "900"
    state: present
    update_cache: true

- name: Install packages
  package:
    name: "{{ cephadm_host_packages }}"
    state: present

- name: Start package services
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - "{{ cephadm_host_services }}"
