# ssh.yml

- name: Create ssh keypair
  openssh_keypair:
    path: /tmp/cephadm_rsa
    size: 4096
  delegate_to: localhost
  run_once: true

- name: Store SSH pubkey as a variable
  command: >-
    cat /tmp/cephadm_rsa.pub
  changed_when:
    - cephadm_pubkey.rc is defined
    - cephadm_pubkey.rc > 0
  delegate_to: localhost
  register: cephadm_pubkey
  run_once: true

- name: Copy SSH keypair to all hosts
  copy:
    src: /tmp/{{ item }}
    dest: ~/.ssh/{{ item }}
    group: root
    mode: "0600"
    owner: root
  with_items:
    - cephadm_rsa
    - cephadm_rsa.pub

- name: Authorize the SSH keypair on all hosts
  authorized_key:
    key: "{{ cephadm_pubkey.stdout_lines[0] }}"
    user: root
    state: present

- name: Add ~/.ssh/config referencing all other hosts
  blockinfile:
    block: |
      {% for host in cephadm_hosts | difference(inventory_hostname) %}
      Host {{ hostvars[host]['ansible_hostname'] }}
          HostName {{ hostvars[host]['ansible_' + interface][ipv].address }}
          IdentityFile ~/.ssh/cephadm_rsa
          PreferredAuthentications publickey
          User root
      {% if not loop.last %}

      {% endif %}
      {% endfor %}
    create: true
    dest: ~/.ssh/config
  vars:
    interface: "{{ cephadm_network_interface_cluster }}"
    ipv: "{{ cephadm_network_ip_version }}"
