# main.yml

- name: Label mgr(s) hosts
  command: >-
    ceph orch host label add {{ hostname }} mgr
  changed_when:
    - result.rc is defined
    - result.rc > 0
  register: result
  vars:
    hostname: "{{ hostvars[item]['ansible_hostname'] }}"
  with_items:
    - "{{ cephadm_hosts_mgrs }}"

- name: Add mgr(s)
  command: >-
    ceph orch apply mgr label:mgr
  changed_when:
    - result.rc is defined
    - result.rc > 0
  register: result
