# main.yml

- name: Disable automated mgr deployment
  command: >-
    ceph orch apply mgr --unmanaged
  changed_when:
    - result.rc is defined
    - result.rc > 0
  register: result

- name: Add "mgr" label to defined hosts
  command: >-
    ceph orch host label add {{ item }} mgr
  changed_when:
    - result.rc is defined
    - result.rc > 0
  register: result
  with_items:
    - "{{ cephadm_hosts_mgrs | difference(inventory_hostname) }}"

- name: Add managers
  command: >-
    ceph orch daemon add mgr {{ item }}:{{ ip_addr }}
  changed_when:
    - result.rc is defined
    - result.rc > 0
  vars:
    ip_addr: "{{ hostvars[item]['ansible_' + cephadm_network_interface_mgrs][cephadm_network_ip_version].address }}"
  with_items:
    - "{{ cephadm_hosts_mgrs | difference(inventory_hostname) }}"
