---
# check.yml

- name: check that hosts meet the requirements
  any_errors_fatal: true
  gather_facts: false
  tags: always
  hosts: all

  pre_tasks:
    - name: check if some version of Python is installed and accessible
      raw: |
        command -v python
      register: python_installed
      changed_when: false
      failed_when: not python_installed

    - name: check if pip is installed and accessible
      raw: |
        command -v pip
      register: pip_installed
      changed_when: false
      failed_when: not pip_installed

    - name: Gather facts for later tasks
      setup:

  tasks:
    - name: check if host OS is supported
      command: uname -a # Trick Ansible into doing our conditionals
      vars:
        target: "{{ ansible_distribution }}-{{ ansible_distribution_version }}"
        targets:
          - Alpine-3.11
          - CentOS-8
          - Ubuntu-18.04
          - Ubuntu-20.04
      changed_when: false
      failed_when: target not in targets
      when: target in targets

- name: check if current configuration is valid for all hosts
  any_errors_fatal: true
  gather_facts: false
  tags: always
  hosts: all

  tasks:
    # TODO: not actually a hard requirement
    - name: check defined network interfaces exist
      failed_when:
        - nic and IPs don't match

    - name: check if hosts are able to reach each other
      command: |-
        ping {{ ansible_facts[item][ipv4][something]}}
      register: ping_result
      with_inventory_items: all
      changed_when: false
      failed_when:
        - ping_result.rc > 0
        - "error" in ping_result.stdout

    - name: check if devices in storage_devices exist
      command: |-
        fdisk {{ item }}
      when: item in storage_devices
      with_items: storage_devices
