---
# check.yml

- name: check that hosts meet the requirements
  any_errors_fatal: true
  gather_facts: false
  tags: always
  hosts: all

  pre_tasks:
    - name: Ensure some version of Python is installed and accessible
      raw: |
        command -v python
      register: python_installed
      changed_when: not python_installed
      failed_when: not python_installed

    - name: Ensure pip is installed and accessible
      raw: |
        command -v pip
      register: pip_installed
      changed_when: not pip_installed
      failed_when: not pip_installed

    - name: Gather facts for later tasks
      setup:

  tasks:
    - name: Determine if host OS is supported
      command: uname -a # Trick Ansible into doing our conditionals
      vars:
        target: "{{ ansible_distribution }}-{{ ansible_distribution_version }}"
        targets:
          - Alpine-3.11
          - CentOS-8
          - Ubuntu-18.04
          - Ubuntu-20.04
      changed_when: false
      failed_when: target not in targets
      when: target in targets
